---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	select_files(select_files)
	load_next_scope_file(load_next_scope_file)
	extract_scope(extract_scope)
	load_catalog(load_catalog)
	match_positions(match_positions)
	build_verdict(build_verdict)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> select_files;
	build_verdict --> finalize;
	extract_scope -.-> load_catalog;
	extract_scope -.-> load_next_scope_file;
	load_catalog --> match_positions;
	load_next_scope_file --> extract_scope;
	match_positions --> build_verdict;
	select_files --> load_next_scope_file;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
